import { Verb, Flashcard, ExamQuestion } from './types';

// ==========================================
// JLPT N5/N4 VERB DATABASE (FULL: 1-150)
// ==========================================
export const VERBS: Verb[] = [
  // --- Godan (Group 1) ---
  { id: 1, kanji: "会う", kana: "あう", romaji: "au", meaning: "To meet", group: "v1", tags: ["n5"] },
  { id: 2, kanji: "洗う", kana: "あらう", romaji: "arau", meaning: "To wash", group: "v1", tags: ["n5"] },
  { id: 3, kanji: "歩く", kana: "あるく", romaji: "aruku", meaning: "To walk", group: "v1", tags: ["n5"] },
  { id: 4, kanji: "言う", kana: "いう", romaji: "iu", meaning: "To say", group: "v1", tags: ["n5"] },
  { id: 5, kanji: "行く", kana: "いく", romaji: "iku", meaning: "To go", group: "v1", tags: ["n5"] },
  { id: 6, kanji: "急ぐ", kana: "いそぐ", romaji: "isogu", meaning: "To hurry", group: "v1", tags: ["n5"] },
  { id: 7, kanji: "歌う", kana: "うたう", romaji: "utau", meaning: "To sing", group: "v1", tags: ["n5"] },
  { id: 8, kanji: "売る", kana: "うる", romaji: "uru", meaning: "To sell", group: "v1", tags: ["n5"] },
  { id: 9, kanji: "置く", kana: "おく", romaji: "oku", meaning: "To put", group: "v1", tags: ["n5"] },
  { id: 10, kanji: "送る", kana: "おくる", romaji: "okuru", meaning: "To send", group: "v1", tags: ["n5"] },
  { id: 11, kanji: "押す", kana: "おす", romaji: "osu", meaning: "To push", group: "v1", tags: ["n5"] },
  { id: 12, kanji: "思う", kana: "おもう", romaji: "omou", meaning: "To think", group: "v1", tags: ["n5"] },
  { id: 13, kanji: "泳ぐ", kana: "およぐ", romaji: "oyogu", meaning: "To swim", group: "v1", tags: ["n5"] },
  { id: 14, kanji: "終わる", kana: "おわる", romaji: "owaru", meaning: "To end", group: "v1", tags: ["n5"] },
  { id: 15, kanji: "買う", kana: "かう", romaji: "kau", meaning: "To buy", group: "v1", tags: ["n5"] },
  { id: 16, kanji: "返す", kana: "かえす", romaji: "kaesu", meaning: "To return (obj)", group: "v1", tags: ["n5"] },
  { id: 17, kanji: "帰る", kana: "かえる", romaji: "kaeru", meaning: "To return home", group: "v1", tags: ["n5"] },
  { id: 18, kanji: "書く", kana: "かく", romaji: "kaku", meaning: "To write", group: "v1", tags: ["n5"] },
  { id: 19, kanji: "貸す", kana: "かす", romaji: "kasu", meaning: "To lend", group: "v1", tags: ["n5"] },
  { id: 20, kanji: "聞く", kana: "きく", romaji: "kiku", meaning: "To listen", group: "v1", tags: ["n5"] },
  { id: 21, kanji: "切る", kana: "きる", romaji: "kiru", meaning: "To cut", group: "v1", tags: ["n5"] },
  { id: 22, kanji: "消す", kana: "けす", romaji: "kesu", meaning: "To turn off", group: "v1", tags: ["n5"] },
  { id: 23, kanji: "困る", kana: "こまる", romaji: "komaru", meaning: "To be troubled", group: "v1", tags: ["n5"] },
  { id: 24, kanji: "咲く", kana: "さく", romaji: "saku", meaning: "To bloom", group: "v1", tags: ["n5"] },
  { id: 25, kanji: "死ぬ", kana: "しぬ", romaji: "shinu", meaning: "To die", group: "v1", tags: ["n5"] },
  { id: 26, kanji: "知る", kana: "しる", romaji: "shiru", meaning: "To know", group: "v1", tags: ["n5"] },
  { id: 27, kanji: "住む", kana: "すむ", romaji: "sumu", meaning: "To live", group: "v1", tags: ["n5"] },
  { id: 28, kanji: "吸う", kana: "すう", romaji: "suu", meaning: "To smoke", group: "v1", tags: ["n5"] },
  { id: 29, kanji: "座る", kana: "すわる", romaji: "suwaru", meaning: "To sit", group: "v1", tags: ["n5"] },
  { id: 30, kanji: "出す", kana: "だす", romaji: "dasu", meaning: "To take out", group: "v1", tags: ["n5"] },
  { id: 31, kanji: "立つ", kana: "たつ", romaji: "tatsu", meaning: "To stand", group: "v1", tags: ["n5"] },
  { id: 32, kanji: "頼む", kana: "たのむ", romaji: "tanomu", meaning: "To request", group: "v1", tags: ["n5"] },
  { id: 33, kanji: "違う", kana: "ちがう", romaji: "chigau", meaning: "To be different", group: "v1", tags: ["n5"] },
  { id: 34, kanji: "使う", kana: "つかう", romaji: "tsukau", meaning: "To use", group: "v1", tags: ["n5"] },
  { id: 35, kanji: "着く", kana: "つく", romaji: "tsuku", meaning: "To arrive", group: "v1", tags: ["n5"] },
  { id: 36, kanji: "作る", kana: "つくる", romaji: "tsukuru", meaning: "To make", group: "v1", tags: ["n5"] },
  { id: 37, kanji: "手伝う", kana: "てつだう", romaji: "tetsudau", meaning: "To help", group: "v1", tags: ["n5"] },
  { id: 38, kanji: "止まる", kana: "とまる", romaji: "tomaru", meaning: "To stop", group: "v1", tags: ["n5"] },
  { id: 39, kanji: "取る", kana: "とる", romaji: "toru", meaning: "To take", group: "v1", tags: ["n5"] },
  { id: 40, kanji: "撮る", kana: "とる", romaji: "toru", meaning: "To take (photo)", group: "v1", tags: ["n5"] },
  { id: 41, kanji: "鳴く", kana: "なく", romaji: "naku", meaning: "To cry (animal)", group: "v1", tags: ["n5"] },
  { id: 42, kanji: "習う", kana: "ならう", romaji: "narau", meaning: "To learn", group: "v1", tags: ["n5"] },
  { id: 43, kanji: "なる", kana: "なる", romaji: "naru", meaning: "To become", group: "v1", tags: ["n5"] },
  { id: 44, kanji: "脱ぐ", kana: "ぬぐ", romaji: "nugu", meaning: "To undress", group: "v1", tags: ["n5"] },
  { id: 45, kanji: "登る", kana: "のぼる", romaji: "noboru", meaning: "To climb", group: "v1", tags: ["n5"] },
  { id: 46, kanji: "飲む", kana: "のむ", romaji: "nomu", meaning: "To drink", group: "v1", tags: ["n5"] },
  { id: 47, kanji: "乗る", kana: "のる", romaji: "noru", meaning: "To ride", group: "v1", tags: ["n5"] },
  { id: 48, kanji: "入る", kana: "はいる", romaji: "hairu", meaning: "To enter", group: "v1", tags: ["n5"] },
  { id: 49, kanji: "履く", kana: "はく", romaji: "haku", meaning: "To wear (shoes)", group: "v1", tags: ["n5"] },
  { id: 50, kanji: "走る", kana: "はしる", romaji: "hashiru", meaning: "To run", group: "v1", tags: ["n5"] },
  { id: 51, kanji: "働く", kana: "はたらく", romaji: "hataraku", meaning: "To work", group: "v1", tags: ["n5"] },
  { id: 52, kanji: "話す", kana: "はなす", romaji: "hanasu", meaning: "To speak", group: "v1", tags: ["n5"] },
  { id: 53, kanji: "引く", kana: "ひく", romaji: "hiku", meaning: "To pull", group: "v1", tags: ["n5"] },
  { id: 54, kanji: "弾く", kana: "ひく", romaji: "hiku", meaning: "To play instrument", group: "v1", tags: ["n5"] },
  { id: 55, kanji: "吹く", kana: "ふく", romaji: "fuku", meaning: "To blow", group: "v1", tags: ["n5"] },
  { id: 56, kanji: "降る", kana: "ふる", romaji: "furu", meaning: "To precipitate", group: "v1", tags: ["n5"] },
  { id: 57, kanji: "曲がる", kana: "まがる", romaji: "magaru", meaning: "To turn", group: "v1", tags: ["n5"] },
  { id: 58, kanji: "待つ", kana: "まつ", romaji: "matsu", meaning: "To wait", group: "v1", tags: ["n5"] },
  { id: 59, kanji: "持つ", kana: "もつ", romaji: "motsu", meaning: "To hold", group: "v1", tags: ["n5"] },
  { id: 60, kanji: "休む", kana: "やすむ", romaji: "yasumu", meaning: "To rest", group: "v1", tags: ["n5"] },
  { id: 61, kanji: "呼ぶ", kana: "よぶ", romaji: "yobu", meaning: "To call", group: "v1", tags: ["n5"] },
  { id: 62, kanji: "読む", kana: "よむ", romaji: "yomu", meaning: "To read", group: "v1", tags: ["n5"] },
  { id: 63, kanji: "分かる", kana: "わかる", romaji: "wakaru", meaning: "To understand", group: "v1", tags: ["n5"] },
  { id: 64, kanji: "渡る", kana: "わたる", romaji: "wataru", meaning: "To cross", group: "v1", tags: ["n5"] },
  { id: 65, kanji: "遊ぶ", kana: "あそぶ", romaji: "asobu", meaning: "To play", group: "v1", tags: ["n5"] },
  { id: 66, kanji: "動く", kana: "うごく", romaji: "ugoku", meaning: "To move", group: "v1", tags: ["n4"] },
  { id: 67, kanji: "選ぶ", kana: "えらぶ", romaji: "erabu", meaning: "To choose", group: "v1", tags: ["n4"] },
  { id: 68, kanji: "怒る", kana: "おこる", romaji: "okoru", meaning: "To get angry", group: "v1", tags: ["n4"] },
  { id: 69, kanji: "落とす", kana: "おとす", romaji: "otosu", meaning: "To drop", group: "v1", tags: ["n4"] },
  { id: 70, kanji: "踊る", kana: "おどる", romaji: "odoru", meaning: "To dance", group: "v1", tags: ["n4"] },
  { id: 71, kanji: "乾く", kana: "かわく", romaji: "kawaku", meaning: "To dry", group: "v1", tags: ["n4"] },
  { id: 72, kanji: "通う", kana: "かよう", romaji: "kayou", meaning: "To commute", group: "v1", tags: ["n4"] },
  { id: 73, kanji: "飾る", kana: "かざる", romaji: "kazaru", meaning: "To decorate", group: "v1", tags: ["n4"] },
  { id: 74, kanji: "勝つ", kana: "かつ", romaji: "katsu", meaning: "To win", group: "v1", tags: ["n4"] },
  { id: 75, kanji: "被る", kana: "かぶる", romaji: "kaburu", meaning: "To wear (hat)", group: "v1", tags: ["n4"] },

  // --- Ichidan (Group 2) ---
  { id: 76, kanji: "開ける", kana: "あける", romaji: "akeru", meaning: "To open", group: "v2", tags: ["n5"] },
  { id: 77, kanji: "あげる", kana: "あげる", romaji: "ageru", meaning: "To give", group: "v2", tags: ["n5"] },
  { id: 78, kanji: "浴びる", kana: "あびる", romaji: "abiru", meaning: "To shower", group: "v2", tags: ["n5"] },
  { id: 79, kanji: "居る", kana: "いる", romaji: "iru", meaning: "To exist (living)", group: "v2", tags: ["n5"] },
  { id: 80, kanji: "入れる", kana: "いれる", romaji: "ireru", meaning: "To insert", group: "v2", tags: ["n5"] },
  { id: 81, kanji: "生まれる", kana: "うまれる", romaji: "umareru", meaning: "To be born", group: "v2", tags: ["n5"] },
  { id: 82, kanji: "起きる", kana: "おきる", romaji: "okiru", meaning: "To wake up", group: "v2", tags: ["n5"] },
  { id: 83, kanji: "教える", kana: "おしえる", romaji: "oshieru", meaning: "To teach", group: "v2", tags: ["n5"] },
  { id: 84, kanji: "覚える", kana: "おぼえる", romaji: "oboeru", meaning: "To remember", group: "v2", tags: ["n5"] },
  { id: 85, kanji: "降りる", kana: "おりる", romaji: "oriru", meaning: "To get off", group: "v2", tags: ["n5"] },
  { id: 86, kanji: "変える", kana: "かえる", romaji: "kaeru", meaning: "To change", group: "v2", tags: ["n4"] },
  { id: 87, kanji: "かける", kana: "かける", romaji: "kakeru", meaning: "To wear (glasses)/Call", group: "v2", tags: ["n5"] },
  { id: 88, kanji: "考える", kana: "かんがえる", romaji: "kangaeru", meaning: "To think/consider", group: "v2", tags: ["n4"] },
  { id: 89, kanji: "借りる", kana: "かりる", romaji: "kariru", meaning: "To borrow", group: "v2", tags: ["n5"] },
  { id: 90, kanji: "消える", kana: "きえる", romaji: "kieru", meaning: "To disappear", group: "v2", tags: ["n5"] },
  { id: 91, kanji: "着る", kana: "きる", romaji: "kiru", meaning: "To wear (upper)", group: "v2", tags: ["n5"] },
  { id: 92, kanji: "答える", kana: "こたえる", romaji: "kotaeru", meaning: "To answer", group: "v2", tags: ["n5"] },
  { id: 93, kanji: "閉める", kana: "しめる", romaji: "shimeru", meaning: "To close", group: "v2", tags: ["n5"] },
  { id: 94, kanji: "信じる", kana: "しんじる", romaji: "shinjiru", meaning: "To believe", group: "v2", tags: ["n4"] },
  { id: 95, kanji: "調べる", kana: "しらべる", romaji: "shiraberu", meaning: "To investigate", group: "v2", tags: ["n4"] },
  { id: 96, kanji: "捨てる", kana: "すてる", romaji: "suteru", meaning: "To throw away", group: "v2", tags: ["n4"] },
  { id: 97, kanji: "食べる", kana: "たべる", romaji: "taberu", meaning: "To eat", group: "v2", tags: ["n5"] },
  { id: 98, kanji: "足りる", kana: "たりる", romaji: "tariru", meaning: "To be sufficient", group: "v2", tags: ["n4"] },
  { id: 99, kanji: "疲れる", kana: "つかれる", romaji: "tsukareru", meaning: "To get tired", group: "v2", tags: ["n5"] },
  { id: 100, kanji: "つける", kana: "つける", romaji: "tsukeru", meaning: "To turn on", group: "v2", tags: ["n5"] },
  { id: 101, kanji: "勤める", kana: "つとめる", romaji: "tsutomeru", meaning: "To work for", group: "v2", tags: ["n5"] },
  { id: 102, kanji: "出る", kana: "でる", romaji: "deru", meaning: "To exit/appear", group: "v2", tags: ["n5"] },
  { id: 103, kanji: "並べる", kana: "ならべる", romaji: "naraberu", meaning: "To line up", group: "v2", tags: ["n5"] },
  { id: 104, kanji: "寝る", kana: "ねる", romaji: "neru", meaning: "To sleep", group: "v2", tags: ["n5"] },
  { id: 105, kanji: "乗り換える", kana: "のりかえる", romaji: "norikaeru", meaning: "To transfer (train)", group: "v2", tags: ["n4"] },
  { id: 106, kanji: "始める", kana: "はじめる", romaji: "hajimeru", meaning: "To begin (sth)", group: "v2", tags: ["n5"] },
  { id: 107, kanji: "晴れる", kana: "はれる", romaji: "hareru", meaning: "To clear up", group: "v2", tags: ["n5"] },
  { id: 108, kanji: "増える", kana: "ふえる", romaji: "fueru", meaning: "To increase", group: "v2", tags: ["n4"] },
  { id: 109, kanji: "褒める", kana: "ほめる", romaji: "homeru", meaning: "To praise", group: "v2", tags: ["n4"] },
  { id: 110, kanji: "負ける", kana: "まける", romaji: "makeru", meaning: "To lose", group: "v2", tags: ["n4"] },
  { id: 111, kanji: "間違える", kana: "まちがえる", romaji: "machigaeru", meaning: "To mistake", group: "v2", tags: ["n4"] },
  { id: 112, kanji: "見える", kana: "みえる", romaji: "mieru", meaning: "To be visible", group: "v2", tags: ["n4"] },
  { id: 113, kanji: "見る", kana: "みる", romaji: "miru", meaning: "To see", group: "v2", tags: ["n5"] },
  { id: 114, kanji: "迎える", kana: "むかえる", romaji: "mukaeru", meaning: "To welcome", group: "v2", tags: ["n4"] },
  { id: 115, kanji: "辞める", kana: "やめる", romaji: "yameru", meaning: "To quit", group: "v2", tags: ["n4"] },
  { id: 116, kanji: "痩せる", kana: "やせる", romaji: "yaseru", meaning: "To lose weight", group: "v2", tags: ["n4"] },
  { id: 117, kanji: "忘れる", kana: "わすれる", romaji: "wasureru", meaning: "To forget", group: "v2", tags: ["n5"] },
  { id: 118, kanji: "割れる", kana: "われる", romaji: "wareru", meaning: "To break/crack", group: "v2", tags: ["n4"] },
  { id: 119, kanji: "遅れる", kana: "おくれる", romaji: "okureru", meaning: "To be late", group: "v2", tags: ["n4"] },
  { id: 120, kanji: "決める", kana: "きめる", romaji: "kimeru", meaning: "To decide", group: "v2", tags: ["n4"] },
  { id: 121, kanji: "知らせる", kana: "しらせる", romaji: "shiraseru", meaning: "To notify", group: "v2", tags: ["n4"] },
  { id: 122, kanji: "建てる", kana: "たてる", romaji: "tateru", meaning: "To build", group: "v2", tags: ["n4"] },
  { id: 123, kanji: "投げる", kana: "なげる", romaji: "nageru", meaning: "To throw", group: "v2", tags: ["n4"] },
  { id: 124, kanji: "逃げる", kana: "にげる", romaji: "nigeru", meaning: "To run away", group: "v2", tags: ["n4"] },
  { id: 125, kanji: "濡れる", kana: "ぬれる", romaji: "nureru", meaning: "To get wet", group: "v2", tags: ["n4"] },
  { id: 126, kanji: "揺れる", kana: "ゆれる", romaji: "yureru", meaning: "To shake", group: "v2", tags: ["n4"] },

  // --- Irregular (Group 3) ---
  { id: 127, kanji: "する", kana: "する", romaji: "suru", meaning: "To do", group: "irr", tags: ["n5"] },
  { id: 128, kanji: "来る", kana: "くる", romaji: "kuru", meaning: "To come", group: "irr", tags: ["n5"] },
  { id: 129, kanji: "勉強する", kana: "べんきょうする", romaji: "benkyousuru", meaning: "To study", group: "irr", tags: ["n5"] },
  { id: 130, kanji: "結婚する", kana: "けっこんする", romaji: "kekkonsuru", meaning: "To marry", group: "irr", tags: ["n4"] },
  { id: 131, kanji: "買い物する", kana: "かいものする", romaji: "kaimonosuru", meaning: "To shop", group: "irr", tags: ["n5"] },
  { id: 132, kanji: "散歩する", kana: "さんぽする", romaji: "sanposuru", meaning: "To stroll", group: "irr", tags: ["n5"] },
  { id: 133, kanji: "旅行する", kana: "りょこうする", romaji: "ryokousuru", meaning: "To travel", group: "irr", tags: ["n5"] },
  { id: 134, kanji: "練習する", kana: "れんしゅうする", romaji: "renshuusuru", meaning: "To practice", group: "irr", tags: ["n5"] },
  { id: 135, kanji: "掃除する", kana: "そうじする", romaji: "soujisuru", meaning: "To clean", group: "irr", tags: ["n5"] },
  { id: 136, kanji: "洗濯する", kana: "せんたくする", romaji: "sentakusuru", meaning: "To do laundry", group: "irr", tags: ["n5"] },
  { id: 137, kanji: "電話する", kana: "でんわする", romaji: "denwasuru", meaning: "To call (phone)", group: "irr", tags: ["n5"] },
  { id: 138, kanji: "心配する", kana: "しんぱいする", romaji: "shinpaisuru", meaning: "To worry", group: "irr", tags: ["n4"] },
  { id: 139, kanji: "説明する", kana: "せつめいする", romaji: "setsumeisuru", meaning: "To explain", group: "irr", tags: ["n4"] },
  { id: 140, kanji: "持ってくる", kana: "もってくる", romaji: "mottekuru", meaning: "To bring (thing)", group: "irr", tags: ["n5"] },
  { id: 141, kanji: "連れて来る", kana: "つれてくる", romaji: "tsuretekuru", meaning: "To bring (person)", group: "irr", tags: ["n5"] },
  { id: 142, kanji: "紹介する", kana: "しょうかいする", romaji: "shoukaisuru", meaning: "To introduce", group: "irr", tags: ["n4"] },
  { id: 143, kanji: "案内する", kana: "あんないする", romaji: "annaisuru", meaning: "To guide", group: "irr", tags: ["n4"] },
  { id: 144, kanji: "運転する", kana: "うんてんする", romaji: "untensuru", meaning: "To drive", group: "irr", tags: ["n4"] },
  { id: 145, kanji: "用意する", kana: "よういする", romaji: "youisuru", meaning: "To prepare", group: "irr", tags: ["n4"] },
  { id: 146, kanji: "予約する", kana: "よやくする", romaji: "yoyakusuru", meaning: "To reserve", group: "irr", tags: ["n4"] },
  { id: 147, kanji: "運動する", kana: "うんどうする", romaji: "undousuru", meaning: "To exercise", group: "irr", tags: ["n4"] },
  { id: 148, kanji: "入院する", kana: "にゅういんする", romaji: "nyuuinsuru", meaning: "To be hospitalized", group: "irr", tags: ["n4"] },
  { id: 149, kanji: "退院する", kana: "たいいんする", romaji: "taiinsuru", meaning: "To leave hospital", group: "irr", tags: ["n4"] },
  { id: 150, kanji: "相談する", kana: "そうだんする", romaji: "soudansuru", meaning: "To consult", group: "irr", tags: ["n4"] },
];

// ==========================================
// KANJI FLASHCARDS (FULL: ~115 Chars)
// ==========================================
export const KANJI_DATA: Flashcard[] = [
  // --- NUMBERS ---
  { id: 1, kanji: "一", readings: { onyomi: ["ICHI"], kunyomi: ["hito"] }, meaning: "One", example: "一人 (Hitori) - One person", level: "N5" },
  { id: 2, kanji: "二", readings: { onyomi: ["NI"], kunyomi: ["futa"] }, meaning: "Two", example: "二月 (Nigatsu) - February", level: "N5" },
  { id: 3, kanji: "三", readings: { onyomi: ["SAN"], kunyomi: ["mit"] }, meaning: "Three", example: "三日 (Mikka) - 3rd day", level: "N5" },
  { id: 4, kanji: "四", readings: { onyomi: ["SHI"], kunyomi: ["yon"] }, meaning: "Four", example: "四人 (Yonin) - Four people", level: "N5" },
  { id: 5, kanji: "五", readings: { onyomi: ["GO"], kunyomi: ["itsu"] }, meaning: "Five", example: "五円 (Goen) - 5 yen", level: "N5" },
  { id: 6, kanji: "六", readings: { onyomi: ["ROKU"], kunyomi: ["mut"] }, meaning: "Six", example: "六つ (Muttsu) - Six things", level: "N5" },
  { id: 7, kanji: "七", readings: { onyomi: ["SHICHI"], kunyomi: ["nana"] }, meaning: "Seven", example: "七月 (Shichigatsu) - July", level: "N5" },
  { id: 8, kanji: "八", readings: { onyomi: ["HACHI"], kunyomi: ["yat"] }, meaning: "Eight", example: "八百屋 (Yaoya) - Greengrocer", level: "N5" },
  { id: 9, kanji: "九", readings: { onyomi: ["KYUU"], kunyomi: ["kokono"] }, meaning: "Nine", example: "九時 (Kuji) - 9 o'clock", level: "N5" },
  { id: 10, kanji: "十", readings: { onyomi: ["JUU"], kunyomi: ["tou"] }, meaning: "Ten", example: "十回 (Jukkai) - 10 times", level: "N5" },
  { id: 11, kanji: "百", readings: { onyomi: ["HYAKU"], kunyomi: ["momo"] }, meaning: "Hundred", example: "三百 (Sanbyaku) - 300", level: "N5" },
  { id: 12, kanji: "千", readings: { onyomi: ["SEN"], kunyomi: ["chi"] }, meaning: "Thousand", example: "三千 (Sanzen) - 3000", level: "N5" },
  { id: 13, kanji: "万", readings: { onyomi: ["MAN"], kunyomi: [] }, meaning: "Ten Thousand", example: "一万円 (Ichimanen) - 10,000 yen", level: "N5" },
  { id: 14, kanji: "円", readings: { onyomi: ["EN"], kunyomi: ["maru"] }, meaning: "Yen/Circle", example: "百円 (Hyakuen) - 100 yen", level: "N5" },

  // --- TIME ---
  { id: 15, kanji: "日", readings: { onyomi: ["NICHI", "JITSU"], kunyomi: ["hi", "bi"] }, meaning: "Day/Sun", example: "日曜日 (Nichiyoubi) - Sunday", level: "N5" },
  { id: 16, kanji: "月", readings: { onyomi: ["GETSU", "GATSU"], kunyomi: ["tsuki"] }, meaning: "Month/Moon", example: "月曜日 (Getsuyoubi) - Monday", level: "N5" },
  { id: 17, kanji: "火", readings: { onyomi: ["KA"], kunyomi: ["hi"] }, meaning: "Fire", example: "火曜日 (Kayoubi) - Tuesday", level: "N5" },
  { id: 18, kanji: "水", readings: { onyomi: ["SUI"], kunyomi: ["mizu"] }, meaning: "Water", example: "水曜日 (Suiyoubi) - Wednesday", level: "N5" },
  { id: 19, kanji: "木", readings: { onyomi: ["MOKU"], kunyomi: ["ki"] }, meaning: "Tree", example: "木曜日 (Mokuyoubi) - Thursday", level: "N5" },
  { id: 20, kanji: "金", readings: { onyomi: ["KIN"], kunyomi: ["kane"] }, meaning: "Gold/Money", example: "金曜日 (Kinyoubi) - Friday", level: "N5" },
  { id: 21, kanji: "土", readings: { onyomi: ["DO"], kunyomi: ["tsuchi"] }, meaning: "Earth/Soil", example: "土曜日 (Doyoubi) - Saturday", level: "N5" },
  { id: 22, kanji: "時", readings: { onyomi: ["JI"], kunyomi: ["toki"] }, meaning: "Time/Hour", example: "時間 (Jikan) - Time", level: "N5" },
  { id: 23, kanji: "分", readings: { onyomi: ["BUN", "FUN"], kunyomi: ["wa"] }, meaning: "Minute/Part", example: "五分 (Gofun) - 5 minutes", level: "N5" },
  { id: 24, kanji: "週", readings: { onyomi: ["SHUU"], kunyomi: [] }, meaning: "Week", example: "来週 (Raishuu) - Next week", level: "N5" },
  { id: 25, kanji: "年", readings: { onyomi: ["NEN"], kunyomi: ["toshi"] }, meaning: "Year", example: "来年 (Rainen) - Next year", level: "N5" },
  { id: 26, kanji: "今", readings: { onyomi: ["KON"], kunyomi: ["ima"] }, meaning: "Now", example: "今日 (Kyou) - Today", level: "N5" },
  { id: 27, kanji: "先", readings: { onyomi: ["SEN"], kunyomi: ["saki"] }, meaning: "Previous", example: "先生 (Sensei) - Teacher", level: "N5" },
  { id: 28, kanji: "来", readings: { onyomi: ["RAI"], kunyomi: ["ku"] }, meaning: "Come/Next", example: "来月 (Raigetsu) - Next month", level: "N5" },
  { id: 29, kanji: "半", readings: { onyomi: ["HAN"], kunyomi: ["naka"] }, meaning: "Half", example: "九時半 (Kujihan) - 9:30", level: "N5" },
  { id: 30, kanji: "毎", readings: { onyomi: ["MAI"], kunyomi: [] }, meaning: "Every", example: "毎日 (Mainichi) - Every day", level: "N5" },
  { id: 31, kanji: "午", readings: { onyomi: ["GO"], kunyomi: [] }, meaning: "Noon", example: "午前 (Gozen) - A.M.", level: "N5" },

  // --- PEOPLE ---
  { id: 32, kanji: "人", readings: { onyomi: ["JIN", "NIN"], kunyomi: ["hito"] }, meaning: "Person", example: "日本人 (Nihonjin) - Japanese person", level: "N5" },
  { id: 33, kanji: "男", readings: { onyomi: ["DAN"], kunyomi: ["otoko"] }, meaning: "Man", example: "男の子 (Otokonoko) - Boy", level: "N5" },
  { id: 34, kanji: "女", readings: { onyomi: ["JO"], kunyomi: ["onna"] }, meaning: "Woman", example: "女の子 (Onnanoko) - Girl", level: "N5" },
  { id: 35, kanji: "子", readings: { onyomi: ["SHI"], kunyomi: ["ko"] }, meaning: "Child", example: "子供 (Kodomo) - Child", level: "N5" },
  { id: 36, kanji: "父", readings: { onyomi: ["FU"], kunyomi: ["chichi"] }, meaning: "Father", example: "お父さん (Otousan) - Father", level: "N5" },
  { id: 37, kanji: "母", readings: { onyomi: ["BO"], kunyomi: ["haha"] }, meaning: "Mother", example: "お母さん (Okaasan) - Mother", level: "N5" },
  { id: 38, kanji: "友", readings: { onyomi: ["YUU"], kunyomi: ["tomo"] }, meaning: "Friend", example: "友達 (Tomodachi) - Friend", level: "N5" },

  // --- NATURE & ELEMENTS ---
  { id: 39, kanji: "山", readings: { onyomi: ["SAN"], kunyomi: ["yama"] }, meaning: "Mountain", example: "富士山 (Fujisan) - Mt. Fuji", level: "N5" },
  { id: 40, kanji: "川", readings: { onyomi: ["SEN"], kunyomi: ["kawa"] }, meaning: "River", example: "川 (Kawa) - River", level: "N5" },
  { id: 41, kanji: "田", readings: { onyomi: ["DEN"], kunyomi: ["ta"] }, meaning: "Rice Field", example: "田中さん (Tanakasan) - Mr. Tanaka", level: "N5" },
  { id: 42, kanji: "天", readings: { onyomi: ["TEN"], kunyomi: ["ama"] }, meaning: "Heaven/Sky", example: "天気 (Tenki) - Weather", level: "N5" },
  { id: 43, kanji: "気", readings: { onyomi: ["KI"], kunyomi: [] }, meaning: "Spirit/Air", example: "元気 (Genki) - Healthy", level: "N5" },
  { id: 44, kanji: "雨", readings: { onyomi: ["U"], kunyomi: ["ame"] }, meaning: "Rain", example: "大雨 (Ooame) - Heavy rain", level: "N5" },
  { id: 45, kanji: "雪", readings: { onyomi: ["SETSU"], kunyomi: ["yuki"] }, meaning: "Snow", example: "雪 (Yuki) - Snow", level: "N5" },

  // --- DIRECTIONS & LOCATIONS ---
  { id: 46, kanji: "上", readings: { onyomi: ["JOU"], kunyomi: ["ue"] }, meaning: "Up/Above", example: "机の上 (Tsukue no ue) - On the desk", level: "N5" },
  { id: 47, kanji: "下", readings: { onyomi: ["KA", "GE"], kunyomi: ["shita"] }, meaning: "Down/Below", example: "地下鉄 (Chikatetsu) - Subway", level: "N5" },
  { id: 48, kanji: "中", readings: { onyomi: ["CHUU"], kunyomi: ["naka"] }, meaning: "Inside/Middle", example: "一日中 (Ichinichijuu) - All day", level: "N5" },
  { id: 49, kanji: "外", readings: { onyomi: ["GAI"], kunyomi: ["soto"] }, meaning: "Outside", example: "外国 (Gaikoku) - Foreign country", level: "N5" },
  { id: 50, kanji: "右", readings: { onyomi: ["U"], kunyomi: ["migi"] }, meaning: "Right", example: "右手 (Migite) - Right hand", level: "N5" },
  { id: 51, kanji: "左", readings: { onyomi: ["SA"], kunyomi: ["hidari"] }, meaning: "Left", example: "左側 (Hidarigawa) - Left side", level: "N5" },
  { id: 52, kanji: "前", readings: { onyomi: ["ZEN"], kunyomi: ["mae"] }, meaning: "Before/Front", example: "名前 (Namae) - Name", level: "N5" },
  { id: 53, kanji: "後", readings: { onyomi: ["GO"], kunyomi: ["usho", "ato"] }, meaning: "After/Behind", example: "午後 (Gogo) - P.M.", level: "N5" },
  { id: 54, kanji: "間", readings: { onyomi: ["KAN"], kunyomi: ["aida"] }, meaning: "Between/Interval", example: "時間 (Jikan) - Time", level: "N5" },
  { id: 55, kanji: "東", readings: { onyomi: ["TOU"], kunyomi: ["higashi"] }, meaning: "East", example: "東京 (Toukyou) - Tokyo", level: "N5" },
  { id: 56, kanji: "西", readings: { onyomi: ["SEI", "SAI"], kunyomi: ["nishi"] }, meaning: "West", example: "関西 (Kansai) - Kansai region", level: "N5" },
  { id: 57, kanji: "南", readings: { onyomi: ["NAN"], kunyomi: ["minami"] }, meaning: "South", example: "南口 (Minamiguchi) - South exit", level: "N5" },
  { id: 58, kanji: "北", readings: { onyomi: ["HOKU"], kunyomi: ["kita"] }, meaning: "North", example: "北海道 (Hokkaidou) - Hokkaido", level: "N5" },

  // --- SCHOOL & BASICS ---
  { id: 59, kanji: "学", readings: { onyomi: ["GAKU"], kunyomi: ["mana"] }, meaning: "Study", example: "学生 (Gakusei) - Student", level: "N5" },
  { id: 60, kanji: "校", readings: { onyomi: ["KOU"], kunyomi: [] }, meaning: "School", example: "学校 (Gakkou) - School", level: "N5" },
  { id: 61, kanji: "生", readings: { onyomi: ["SEI", "SHOU"], kunyomi: ["i", "u", "na"] }, meaning: "Life/Student", example: "先生 (Sensei) - Teacher", level: "N5" },
  { id: 62, kanji: "本", readings: { onyomi: ["HON"], kunyomi: ["moto"] }, meaning: "Book/Origin", example: "日本 (Nihon) - Japan", level: "N5" },
  { id: 63, kanji: "語", readings: { onyomi: ["GO"], kunyomi: ["kata"] }, meaning: "Language", example: "日本語 (Nihongo) - Japanese", level: "N5" },
  { id: 64, kanji: "何", readings: { onyomi: ["KA"], kunyomi: ["nani", "nan"] }, meaning: "What", example: "何時 (Nanji) - What time?", level: "N5" },

  // --- BODY & HEALTH ---
  { id: 65, kanji: "口", readings: { onyomi: ["KOU", "KU"], kunyomi: ["kuchi"] }, meaning: "Mouth", example: "出口 (Deguchi) - Exit", level: "N5" },
  { id: 66, kanji: "目", readings: { onyomi: ["MOKU"], kunyomi: ["me"] }, meaning: "Eye", example: "目 (Me) - Eye", level: "N5" },
  { id: 67, kanji: "耳", readings: { onyomi: ["JI"], kunyomi: ["mimi"] }, meaning: "Ear", example: "耳 (Mimi) - Ear", level: "N5" },
  { id: 68, kanji: "手", readings: { onyomi: ["SHU"], kunyomi: ["te"] }, meaning: "Hand", example: "手紙 (Tegami) - Letter", level: "N5" },
  { id: 69, kanji: "足", readings: { onyomi: ["SOKU"], kunyomi: ["ashi"] }, meaning: "Foot/Leg", example: "足りる (Tariru) - To suffice", level: "N5" },
  { id: 70, kanji: "力", readings: { onyomi: ["RYOKU", "RIKI"], kunyomi: ["chikara"] }, meaning: "Power", example: "協力 (Kyouryoku) - Cooperation", level: "N4" },

  // --- ADJECTIVES (OPPOSITES) ---
  { id: 71, kanji: "大", readings: { onyomi: ["DAI", "TAI"], kunyomi: ["oo"] }, meaning: "Big", example: "大学 (Daigaku) - University", level: "N5" },
  { id: 72, kanji: "小", readings: { onyomi: ["SHOU"], kunyomi: ["chii"] }, meaning: "Small", example: "小学校 (Shougakkou) - Elementary school", level: "N5" },
  { id: 73, kanji: "高", readings: { onyomi: ["KOU"], kunyomi: ["taka"] }, meaning: "High/Expensive", example: "高校 (Koukou) - High school", level: "N5" },
  { id: 74, kanji: "安", readings: { onyomi: ["AN"], kunyomi: ["yasu"] }, meaning: "Cheap/Safe", example: "安い (Yasui) - Cheap", level: "N5" },
  { id: 75, kanji: "新", readings: { onyomi: ["SHIN"], kunyomi: ["atara"] }, meaning: "New", example: "新聞 (Shinbun) - Newspaper", level: "N5" },
  { id: 76, kanji: "古", readings: { onyomi: ["KO"], kunyomi: ["furu"] }, meaning: "Old", example: "古い (Furui) - Old", level: "N5" },
  { id: 77, kanji: "多", readings: { onyomi: ["TA"], kunyomi: ["oo"] }, meaning: "Many", example: "多い (Ooi) - Many", level: "N5" },
  { id: 78, kanji: "少", readings: { onyomi: ["SHOU"], kunyomi: ["suku", "suko"] }, meaning: "Few", example: "少し (Sukoshi) - A little", level: "N5" },
  { id: 79, kanji: "長", readings: { onyomi: ["CHOU"], kunyomi: ["naga"] }, meaning: "Long", example: "社長 (Shachou) - Company president", level: "N5" },
  { id: 80, kanji: "短", readings: { onyomi: ["TAN"], kunyomi: ["mijika"] }, meaning: "Short", example: "短い (Mijikai) - Short", level: "N4" },
  { id: 81, kanji: "白", readings: { onyomi: ["HAKU"], kunyomi: ["shiro"] }, meaning: "White", example: "白い (Shiroi) - White", level: "N5" },
  { id: 82, kanji: "黒", readings: { onyomi: ["KOKU"], kunyomi: ["kuro"] }, meaning: "Black", example: "黒い (Kuroi) - Black", level: "N4" },
  { id: 83, kanji: "赤", readings: { onyomi: ["SEKI"], kunyomi: ["aka"] }, meaning: "Red", example: "赤ちゃん (Akachan) - Baby", level: "N4" },
  { id: 84, kanji: "青", readings: { onyomi: ["SEI"], kunyomi: ["ao"] }, meaning: "Blue", example: "青い (Aoi) - Blue", level: "N4" },

  // --- ACTIONS ---
  { id: 85, kanji: "行", readings: { onyomi: ["KOU", "GYOU"], kunyomi: ["i"] }, meaning: "Go", example: "旅行 (Ryokou) - Travel", level: "N5" },
  { id: 86, kanji: "来", readings: { onyomi: ["RAI"], kunyomi: ["ku"] }, meaning: "Come", example: "来週 (Raishuu) - Next week", level: "N5" },
  { id: 87, kanji: "食", readings: { onyomi: ["SHOKU"], kunyomi: ["ta"] }, meaning: "Eat", example: "食事 (Shokuji) - Meal", level: "N5" },
  { id: 88, kanji: "飲", readings: { onyomi: ["IN"], kunyomi: ["no"] }, meaning: "Drink", example: "飲み物 (Nomimono) - Drink", level: "N5" },
  { id: 89, kanji: "見", readings: { onyomi: ["KEN"], kunyomi: ["mi"] }, meaning: "See", example: "見物 (Kenbutsu) - Sightseeing", level: "N5" },
  { id: 90, kanji: "聞", readings: { onyomi: ["BUN"], kunyomi: ["ki"] }, meaning: "Hear", example: "新聞 (Shinbun) - Newspaper", level: "N5" },
  { id: 91, kanji: "書", readings: { onyomi: ["SHO"], kunyomi: ["ka"] }, meaning: "Write", example: "辞書 (Jisho) - Dictionary", level: "N5" },
  { id: 92, kanji: "読", readings: { onyomi: ["DOKU"], kunyomi: ["yo"] }, meaning: "Read", example: "読書 (Dokusho) - Reading", level: "N5" },
  { id: 93, kanji: "言", readings: { onyomi: ["GEN"], kunyomi: ["i"] }, meaning: "Say", example: "言葉 (Kotoba) - Word", level: "N5" },
  { id: 94, kanji: "話", readings: { onyomi: ["WA"], kunyomi: ["hana"] }, meaning: "Talk", example: "電話 (Denwa) - Telephone", level: "N5" },
  { id: 95, kanji: "立", readings: { onyomi: ["RITSU"], kunyomi: ["ta"] }, meaning: "Stand", example: "国立 (Kokuritsu) - National", level: "N5" },
  { id: 96, kanji: "待", readings: { onyomi: ["TAI"], kunyomi: ["ma"] }, meaning: "Wait", example: "招待 (Shoutai) - Invitation", level: "N4" },
  { id: 97, kanji: "出", readings: { onyomi: ["SHUTSU"], kunyomi: ["de", "da"] }, meaning: "Exit", example: "出口 (Deguchi) - Exit", level: "N5" },
  { id: 98, kanji: "入", readings: { onyomi: ["NYUU"], kunyomi: ["hai", "i"] }, meaning: "Enter", example: "入口 (Iriguchi) - Entrance", level: "N5" },
  { id: 99, kanji: "休", readings: { onyomi: ["KYUU"], kunyomi: ["yasu"] }, meaning: "Rest", example: "休み (Yasumi) - Holiday", level: "N5" },

  // --- SOCIETY & PLACES ---
  { id: 100, kanji: "名", readings: { onyomi: ["MEI", "MYOU"], kunyomi: ["na"] }, meaning: "Name", example: "名前 (Namae) - Name", level: "N5" },
  { id: 101, kanji: "道", readings: { onyomi: ["DOU"], kunyomi: ["michi"] }, meaning: "Road/Way", example: "書道 (Shodou) - Calligraphy", level: "N5" },
  { id: 102, kanji: "駅", readings: { onyomi: ["EKI"], kunyomi: [] }, meaning: "Station", example: "駅前 (Ekimae) - Before station", level: "N5" },
  { id: 103, kanji: "車", readings: { onyomi: ["SHA"], kunyomi: ["kuruma"] }, meaning: "Car", example: "電車 (Densha) - Train", level: "N5" },
  { id: 104, kanji: "電", readings: { onyomi: ["DEN"], kunyomi: [] }, meaning: "Electricity", example: "電気 (Denki) - Electricity", level: "N5" },
  { id: 105, kanji: "社", readings: { onyomi: ["SHA"], kunyomi: ["yashiro"] }, meaning: "Company/Shrine", example: "会社 (Kaisha) - Company", level: "N5" },
  { id: 106, kanji: "国", readings: { onyomi: ["KOKU"], kunyomi: ["kuni"] }, meaning: "Country", example: "中国 (Chuugoku) - China", level: "N5" },
  { id: 107, kanji: "町", readings: { onyomi: ["CHOU"], kunyomi: ["machi"] }, meaning: "Town", example: "町長 (Chouchou) - Mayor", level: "N4" },
  { id: 108, kanji: "村", readings: { onyomi: ["SON"], kunyomi: ["mura"] }, meaning: "Village", example: "村人 (Murabito) - Villager", level: "N4" },
  { id: 109, kanji: "空", readings: { onyomi: ["KUU"], kunyomi: ["sora", "a"] }, meaning: "Sky/Empty", example: "空気 (Kuuki) - Air", level: "N5" },
  { id: 110, kanji: "花", readings: { onyomi: ["KA"], kunyomi: ["hana"] }, meaning: "Flower", example: "花火 (Hanabi) - Fireworks", level: "N5" },
  { id: 111, kanji: "魚", readings: { onyomi: ["GYO"], kunyomi: ["sakana"] }, meaning: "Fish", example: "金魚 (Kingyo) - Goldfish", level: "N5" },
  { id: 112, kanji: "肉", readings: { onyomi: ["NIKU"], kunyomi: [] }, meaning: "Meat", example: "牛肉 (Gyuuniku) - Beef", level: "N4" },
  { id: 113, kanji: "買", readings: { onyomi: ["BAI"], kunyomi: ["ka"] }, meaning: "Buy", example: "買い物 (Kaimono) - Shopping", level: "N5" },
  { id: 114, kanji: "止", readings: { onyomi: ["SHI"], kunyomi: ["to"] }, meaning: "Stop", example: "中止 (Chuushi) - Cancellation", level: "N4" },
  { id: 115, kanji: "切", readings: { onyomi: ["SETSU"], kunyomi: ["ki"] }, meaning: "Cut", example: "切手 (Kitte) - Stamp", level: "N4" },
];

// ==========================================
// EXAM QUESTIONS (FULL: 50 Questions)
// ==========================================
export const EXAM_QUESTIONS: ExamQuestion[] = [
  // --- PARTICLES (1-10) ---
  { id: 1, category: 'grammar', question: "私は寿司 ___ 食べます。", options: ["が", "を", "に", "へ"], correctIndex: 1, explanation: "'Wo' marks the object of the verb (eating sushi)." },
  { id: 2, category: 'grammar', question: "バス ___ 行きます。", options: ["で", "に", "を", "が"], correctIndex: 0, explanation: "'De' indicates the means/method of transport." },
  { id: 3, category: 'grammar', question: "日曜日に友達 ___ 会いました。", options: ["を", "が", "に", "で"], correctIndex: 2, explanation: "'Ni' indicates the target person you meet." },
  { id: 4, category: 'grammar', question: "机の上に本 ___ あります。", options: ["が", "は", "を", "に"], correctIndex: 0, explanation: "'Ga' is used with Arimasu to introduce the subject of existence." },
  { id: 5, category: 'grammar', question: "毎日7時 ___ 起きます。", options: ["に", "で", "を", "へ"], correctIndex: 0, explanation: "'Ni' marks a specific point in time." },
  { id: 6, category: 'grammar', question: "図書館 ___ 勉強します。", options: ["に", "で", "を", "へ"], correctIndex: 1, explanation: "'De' marks the location where an action takes place." },
  { id: 7, category: 'grammar', question: "東京 ___ 行きたいです。", options: ["を", "で", "へ", "が"], correctIndex: 2, explanation: "'He' (pronounced 'e') indicates direction of movement." },
  { id: 8, category: 'grammar', question: "猫 ___ 好きです。", options: ["が", "を", "で", "に"], correctIndex: 0, explanation: "Suki (Like) requires 'Ga' for the object liked." },
  { id: 9, category: 'grammar', question: "弟 ___ 背が高いです。", options: ["は", "が", "の", "を"], correctIndex: 0, explanation: "'Wa' marks the topic (As for my younger brother...)." },
  { id: 10, category: 'grammar', question: "これ ___ ください。", options: ["を", "は", "が", "で"], correctIndex: 0, explanation: "'Wo' marks the object being requested." },

  // --- CONJUGATIONS & FORMS (11-20) ---
  { id: 11, category: 'grammar', question: "明日、映画を ___ か。", options: ["見ます", "見ません", "見ましょう", "見て"], correctIndex: 2, explanation: "Mashou ka = Shall we?" },
  { id: 12, category: 'grammar', question: "ここで写真を ___ ください。", options: ["撮って", "撮りて", "撮て", "撮るて"], correctIndex: 0, explanation: "Toru -> Totte (Te-form for requests)." },
  { id: 13, category: 'grammar', question: "昨日は雨が ___。", options: ["降るでした", "降りました", "降りたです", "降りますでした"], correctIndex: 1, explanation: "Mashita is the polite past form." },
  { id: 14, category: 'grammar', question: "まだご飯を ___。", options: ["食べました", "食べていません", "食べません", "食べない"], correctIndex: 1, explanation: "Te imasen = Haven't done yet." },
  { id: 15, category: 'grammar', question: "この本は ___ ないです。", options: ["おもしろく", "おもしろい", "おもしろ", "おもしろくて"], correctIndex: 0, explanation: "i-adjective negative: remove 'i', add 'kunai'." },
  { id: 16, category: 'grammar', question: "あの人は ___ です。", options: ["元気な", "元気", "元気に", "元気の"], correctIndex: 1, explanation: "Na-adjectives don't use 'na' at the end of a sentence." },
  { id: 17, category: 'grammar', question: "日本語を ___ ことができます。", options: ["話す", "話します", "話して", "話した"], correctIndex: 0, explanation: "Dictionary form + koto ga dekimasu = Can do." },
  { id: 18, category: 'grammar', question: "週末は家でテレビを ___ します。", options: ["見た", "見て", "見たり", "見と"], correctIndex: 2, explanation: "Tari... tari shimasu lists representative actions." },
  { id: 19, category: 'grammar', question: "部屋を ___ しました。", options: ["きれい", "きれいに", "きれいな", "きれいだ"], correctIndex: 1, explanation: "Na-adj + ni suru = To make (condition)." },
  { id: 20, category: 'grammar', question: "薬を ___ ほうがいいです。", options: ["飲む", "飲んだ", "飲んで", "飲み"], correctIndex: 1, explanation: "Ta-form + hou ga ii = Had better / Should." },

  // --- VOCABULARY & KANJI (21-35) ---
  { id: 21, category: 'vocab', question: "「先生」の読み方は何ですか。", options: ["せんせい", "がくせい", "せんしゅう", "ぜんせい"], correctIndex: 0, explanation: "Sensei = Teacher." },
  { id: 22, category: 'vocab', question: "「今日」の読み方は何ですか。", options: ["きのう", "きょう", "あした", "こんいち"], correctIndex: 1, explanation: "Kyou = Today." },
  { id: 23, category: 'vocab', question: "「食べる」の意味は何ですか。", options: ["To eat", "To read", "To write", "To drink"], correctIndex: 0, explanation: "Taberu = To eat." },
  { id: 24, category: 'vocab', question: "「右」の反対は何ですか。", options: ["左", "上", "下", "前"], correctIndex: 0, explanation: "Migi (Right) <-> Hidari (Left)." },
  { id: 25, category: 'vocab', question: "「新しい」の反対は何ですか。", options: ["古い", "高い", "安い", "小さい"], correctIndex: 0, explanation: "Atarashii (New) <-> Furui (Old)." },
  { id: 26, category: 'vocab', question: "「毎朝」の読み方は何ですか。", options: ["まいあさ", "まいにち", "まいばん", "まいしゅう"], correctIndex: 0, explanation: "Maiasa = Every morning." },
  { id: 27, category: 'vocab', question: "「出口」はどこですか。", options: ["Exit", "Entrance", "Ticket gate", "Toilet"], correctIndex: 0, explanation: "Deguchi = Exit." },
  { id: 28, category: 'vocab', question: "この部屋はとても ___ です。", options: ["暗い", "黒い", "悪い", "甘い"], correctIndex: 0, explanation: "Kurai = Dark (fits context of a room)." },
  { id: 29, category: 'vocab', question: "「切手」を買います。", options: ["きって", "きっぷ", "きもち", "きもの"], correctIndex: 0, explanation: "Kitte = Stamp." },
  { id: 30, category: 'vocab', question: "「一万円」の読み方は何ですか。", options: ["いちまんえん", "いちせんえん", "ひゃくまんえん", "じゅうまんえん"], correctIndex: 0, explanation: "Ichimanen = 10,000 yen." },
  { id: 31, category: 'vocab', question: "「雨」が降っています。", options: ["あめ", "ゆき", "くもり", "はれ"], correctIndex: 0, explanation: "Ame = Rain." },
  { id: 32, category: 'vocab', question: "「駅」まで歩きます。", options: ["えき", "みち", "みせ", "いえ"], correctIndex: 0, explanation: "Eki = Station." },
  { id: 33, category: 'vocab', question: "「名前」を書いてください。", options: ["なまえ", "ゆうめい", "めいし", "ひらがな"], correctIndex: 0, explanation: "Namae = Name." },
  { id: 34, category: 'vocab', question: "「時計」を見ます。", options: ["とけい", "じかん", "とき", "ふん"], correctIndex: 0, explanation: "Tokei = Clock/Watch." },
  { id: 35, category: 'vocab', question: "「黒い」猫がいます。", options: ["くろい", "しろい", "あかい", "あおい"], correctIndex: 0, explanation: "Kuroi = Black." },

  // --- READING & CONTEXT (36-50) ---
  { id: 36, category: 'reading', question: "A: ありがとう。 B: ___。", options: ["どういたしまして", "ごめんなさい", "いただきます", "ごちそうさま"], correctIndex: 0, explanation: "Standard response to thank you: Douitashimashite." },
  { id: 37, category: 'reading', question: "A: いってきます。 B: ___。", options: ["いってらっしゃい", "おかえりなさい", "ただいま", "こんばんは"], correctIndex: 0, explanation: "Leaving home greeting pair." },
  { id: 38, category: 'reading', question: "A: はじめまして。 B: ___。", options: ["こちらこそ、よろしく", "さようなら", "お元気ですか", "失礼します"], correctIndex: 0, explanation: "Meeting for the first time." },
  { id: 39, category: 'reading', question: "朝、起きてから何を言いますか。", options: ["おはようございます", "こんにちは", "こんばんは", "おやすみなさい"], correctIndex: 0, explanation: "Morning greeting." },
  { id: 40, category: 'reading', question: "寝る前に何を言いますか。", options: ["おやすみなさい", "おはよう", "ありがとう", "さようなら"], correctIndex: 0, explanation: "Before sleeping." },
  { id: 41, category: 'grammar', question: "私は日本料理 ___ 好きです。", options: ["が", "を", "で", "に"], correctIndex: 0, explanation: "Suki takes Ga." },
  { id: 42, category: 'grammar', question: "昨日、デパートへ ___ 行きました。", options: ["買い物に", "買い物", "買い物を", "買い物が"], correctIndex: 0, explanation: "Purpose of movement: Stem + ni ikimasu." },
  { id: 43, category: 'grammar', question: "このペンは ___ ですか。", options: ["だれ", "だれの", "どれ", "どの"], correctIndex: 1, explanation: "Dare no = Whose." },
  { id: 44, category: 'grammar', question: "それは ___ の鞄ですか。", options: ["私", "私に", "私が", "私を"], correctIndex: 0, explanation: "Watashi no = Mine." },
  { id: 45, category: 'grammar', question: "あそこで ___ してください。", options: ["待って", "待つて", "待ちて", "待て"], correctIndex: 0, explanation: "Matsu -> Matte." },
  { id: 46, category: 'grammar', question: "タバコを ___ ください。", options: ["吸わないで", "吸わなくて", "吸わない", "吸うない"], correctIndex: 0, explanation: "Negative request: Nai-form + de kudasai." },
  { id: 47, category: 'grammar', question: "お金が ___ から、買いません。", options: ["ない", "なく", "ありません", "ないで"], correctIndex: 0, explanation: "Kara (because) connects to plain form 'nai'." },
  { id: 48, category: 'grammar', question: "どのぐらい日本語を勉強しましたか。", options: ["3ヶ月", "3月", "3日", "3時"], correctIndex: 0, explanation: "Duration involves 'kagetsu' for months." },
  { id: 49, category: 'grammar', question: "あの店は料理が ___、安いです。", options: ["おいしくて", "おいしい", "おいしいで", "おいしく"], correctIndex: 0, explanation: "Linking i-adjectives: remove i, add kute." },
  { id: 50, category: 'grammar', question: "田中さんは ___ 人ですか。", options: ["どんな", "なんの", "どう", "どの"], correctIndex: 0, explanation: "Donna = What kind of." },

  // --- EXPANSION (51-80) ---
  { id: 51, category: 'grammar', question: "私は日本のアニメ ___ 好きです。", options: ["が", "を", "に", "で"], correctIndex: 0, explanation: "Suki/Kirai requires 'Ga'." },
  { id: 52, category: 'grammar', question: "図書館で本を ___。", options: ["借りました", "借りますした", "借りでした", "借りるました"], correctIndex: 0, explanation: "Karimasu -> Karimashita (Polite Past)." },
  { id: 53, category: 'vocab', question: "「お元気ですか。」「はい、___。」", options: ["元気です", "元気します", "元気ありません", "元気でした"], correctIndex: 0, explanation: "Standard response: Hai, genki desu." },
  { id: 54, category: 'grammar', question: "この靴はいくら ___。", options: ["ですか", "ますか", "ありませんか", "でしたか"], correctIndex: 0, explanation: "Asking price: Ikura desu ka." },
  { id: 55, category: 'vocab', question: "「銀行」の読み方は何ですか。", options: ["ぎんこう", "きんこう", "ぎんごう", "がっこう"], correctIndex: 0, explanation: "Ginkou = Bank." },
  { id: 56, category: 'grammar', question: "机の上に ___ があります。", options: ["何も", "何か", "何で", "何"], correctIndex: 1, explanation: "Nanika = Something." },
  { id: 57, category: 'grammar', question: "テレビを ___ ご飯を食べます。", options: ["見ながら", "見で", "見ると", "見るから"], correctIndex: 0, explanation: "Verb Stem + nagara = While doing..." },
  { id: 58, category: 'grammar', question: "教室に学生が ___ います。", options: ["三人", "三つ", "三枚", "三本"], correctIndex: 0, explanation: "Counter for people: Nin." },
  { id: 59, category: 'grammar', question: "昨日、友達に ___。", options: ["会いました", "会ったです", "会うました", "会いでした"], correctIndex: 0, explanation: "Au -> Aimashita (Met)." },
  { id: 60, category: 'grammar', question: "もっと ___ 書いてください。", options: ["ゆっくり", "はやく", "だんだん", "あまり"], correctIndex: 0, explanation: "Yukkuri = Slowly." },
  { id: 61, category: 'grammar', question: "この漢字は ___ ですか。", options: ["難しい", "難しく", "難しくて", "難しな"], correctIndex: 0, explanation: "Adjective ending sentence stays in dictionary form + desu." },
  { id: 62, category: 'vocab', question: "「来週」の意味は何ですか。", options: ["Next week", "Last week", "This week", "Next month"], correctIndex: 0, explanation: "Raishuu = Next week." },
  { id: 63, category: 'grammar', question: "コーヒーと紅茶とどちらが好きですか。コーヒー ___ 好きです。", options: ["のほうが", "ほうが", "より", "が"], correctIndex: 0, explanation: "Comparison answer: X no hou ga suki desu." },
  { id: 64, category: 'grammar', question: "夏休みはどこ ___ 行きませんでした。", options: ["へも", "へ", "に", "を"], correctIndex: 0, explanation: "Negative scope: Question Word + mo + Negative." },
  { id: 65, category: 'vocab', question: "「青い」シャツを着ています。", options: ["あおい", "あかい", "しろい", "くろい"], correctIndex: 0, explanation: "Aoi = Blue." },
  { id: 66, category: 'grammar', question: "バスに ___。", options: ["乗ります", "入ります", "行きます", "来ます"], correctIndex: 0, explanation: "Norimasu = To ride/get on (takes 'ni')." },
  { id: 67, category: 'grammar', question: "それを ___ ください。", options: ["見せて", "見て", "見えて", "見る"], correctIndex: 0, explanation: "Miseru = To show. Misete kudasai." },
  { id: 68, category: 'vocab', question: "12時です。___ を食べましょう。", options: ["昼ご飯", "朝ご飯", "晩ご飯", "おやつ"], correctIndex: 0, explanation: "Hirugohan = Lunch." },
  { id: 69, category: 'grammar', question: "会社へ ___ 行きますか。バスで行きます。", options: ["どうやって", "どれ", "どの", "どちら"], correctIndex: 0, explanation: "Douyatte = How (means of transport)." },
  { id: 70, category: 'grammar', question: "宿題を ___ いけません。", options: ["しなくては", "しないで", "しないて", "するには"], correctIndex: 0, explanation: "Must do: Nai-form (drop i) + nakute wa ikemasen." },
  { id: 71, category: 'grammar', question: "雨が ___ そうです。", options: ["降り", "降る", "降って", "降ろ"], correctIndex: 0, explanation: "Stem + sou desu = Looks like it will..." },
  { id: 72, category: 'grammar', question: "日本語がうまく ___ なりました。", options: ["話せるように", "話すように", "話してように", "話したように"], correctIndex: 0, explanation: "Potential + you ni naru = Become able to..." },
  { id: 73, category: 'vocab', question: "「弟」は誰ですか。", options: ["Younger brother", "Older brother", "Younger sister", "Father"], correctIndex: 0, explanation: "Otouto = Younger brother." },
  { id: 74, category: 'grammar', question: "あの人は ___ かもしれません。", options: ["学生", "学生だ", "学生に", "学生く"], correctIndex: 0, explanation: "Noun/Na-adj + kamoshiremasen (Might be)." },
  { id: 75, category: 'grammar', question: "テストが ___ 、嬉しいです。", options: ["終わって", "終わりて", "終わて", "終わる"], correctIndex: 0, explanation: "Reason/Cause: Te-form." },
  { id: 76, category: 'vocab', question: "「荷物」を持ちましょうか。", options: ["にもつ", "かいもの", "たべもの", "のりもの"], correctIndex: 0, explanation: "Nimotsu = Luggage/Baggage." },
  { id: 77, category: 'grammar', question: "ここでタバコを ___ いけません。", options: ["吸っては", "吸ては", "吸いては", "吸うては"], correctIndex: 0, explanation: "Prohibition: Te-form + wa ikemasen." },
  { id: 78, category: 'vocab', question: "「大切」な友達。", options: ["たいせつ", "だいじ", "しんせつ", "べんり"], correctIndex: 0, explanation: "Taisetsu = Important/Precious." },
  { id: 79, category: 'grammar', question: "私は来年、日本へ ___ つもりです。", options: ["行く", "行きます", "行って", "行った"], correctIndex: 0, explanation: "Intention: Dictionary form + tsumori desu." },
  { id: 80, category: 'grammar', question: "映画を ___ 後で、食事をしました。", options: ["見た", "見て", "見る", "見ない"], correctIndex: 0, explanation: "After doing X: Ta-form + ato de." },
];